FROM python:3.9-slim

WORKDIR /app

COPY lfi.py /app
COPY requirements.txt /app
COPY templates /app/templates
COPY static /app/static


RUN pip install --no-cache-dir  -r requirements.txt

EXPOSE 5000

CMD ["python", "lfi.py"]